export default {
    baseUrl: 'http://localhost:5000/api/',
    token: 'http://localhost:5000/api/token',
    profile_data: 'http://localhost:5000/api/profile',
    roles_data: 'http://localhost:5000/api/roles/',
    permissions_data: 'http://localhost:5000/api/permissions/',
    create_user: 'http://localhost:5000/api/register',
    courses_data: 'http://localhost:5000/api/courses',
    resources_data: 'http://localhost:5000/api/resources',
    locals_data: 'http://localhost:5000/api/locals',
    groups_data: 'http://localhost:5000/api/groups',
    tags_data: 'http://localhost:5000/api/tags',
    query_events: 'http://localhost:5000/api/events',
    event_info: 'http://localhost:5000/api/events/',
}