export default {
    baseUrl: 'http://localhost:5000/api/',
    token: 'http://localhost:5000/api/token',
    profile: 'http://localhost:5000/api/profile',
    roles_data: 'http://localhost:5000/api/roles',
    permissions: 'http://localhost:5000/api/permissions',
    register: 'http://localhost:5000/api/register',
    courses: 'http://localhost:5000/api/courses',
    resources: 'http://localhost:5000/api/resources',
    locals: 'http://localhost:5000/api/locals',
    groups: 'http://localhost:5000/api/groups',
    tags: 'http://localhost:5000/api/tags',
    users: 'http://localhost:5000/api/users',
    events: 'http://localhost:5000/api/events',
}