"""empty message

Revision ID: 1286f32e7fc6
Revises: 532e901eaf24
Create Date: 2019-03-14 11:56:40.208842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1286f32e7fc6'
down_revision = '532e901eaf24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    op.drop_column('user', 'activated')
    # ### end Alembic commands ###
