"""empty message

Revision ID: f36bd9ab57d6
Revises: 6a2d57f5acdc
Create Date: 2019-03-24 13:29:24.002008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36bd9ab57d6'
down_revision = '6a2d57f5acdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('career', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'career')
    # ### end Alembic commands ###
